### ISSUE TITLE
argocd version

### ISSUE THREAD

**Issue by fredcb** [redhat-developer/gitops-operator#100]
Hi
I can't seem to find info about which version of argocd  this operator builds on.  Which version is it today? And, if  not version 1.8 already, when do you plan to release that version with the gitops operator?

**Comment by iam-veeramalla** [comment]
@fredcb it is 1.8.7 currently and we have a GA planned this month which is planned for argo-cd 2.0.

**Comment by fredcb** [comment]
Very good! Thanks for quick answer!
