### ISSUE TITLE
gitopsservice is not namespaced, but the console requests api on openshift-github

### ISSUE THREAD

**Issue by rgordill** [redhat-developer/gitops-operator#101]
**Describe the bug**
The gitops service is not namespaced. Sample once installed:

```
apiVersion: pipelines.openshift.io/v1alpha1
kind: GitopsService
metadata:
  creationTimestamp: "2021-04-03T20:55:40Z"
  generation: 1
  managedFields:
  - apiVersion: pipelines.openshift.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec: {}
      f:status: {}
    manager: gitops-operator
    operation: Update
    time: "2021-04-03T20:55:40Z"
  name: cluster
  resourceVersion: "35378"
  selfLink: /apis/pipelines.openshift.io/v1alpha1/gitopsservices/cluster
  uid: d7520894-fa57-40c7-a939-fc01c37e7e10
spec: {}
```

However the console considers it namespace for searching at:

https://console-openshift-console.apps-crc.testing/api/kubernetes/apis/pipelines.openshift.io/v1alpha1/namespaces/openshift-gitops/gitopsservices?limit=250

Instead of

https://console-openshift-console.apps-crc.testing/api/kubernetes/apis/pipelines.openshift.io/v1alpha1/gitopsservices?limit=250

**To Reproduce**
1. Install an OpenShift 4.7.2 (I have used CRC)
2. Install openshift-gitops operator
3. After the install finishes ok, go to gitops services or all instances tab
4. See a 404 error

**Expected behavior**
The instances on those resources displayed

**Screenshots**
![gitops](https://user-images.githubusercontent.com/21176597/113494972-f98f2500-94ed-11eb-9722-09c91f9b071a.png)

**Additional context**

**Comment by iam-veeramalla** [comment]
@rgordill which build are you using. @chetan-rns  got it fixed as part of https://github.com/openshift/console/pull/8379

**Comment by rgordill** [comment]
OCP 4.7.2, as in https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.7.2/release.txt, which is the latest for CRC. I assume as this release is from March 5th, this commit is not included. I will wait for next CRC release to test it.

Thanks.
