### ISSUE TITLE
ArgoCD 2.0 support?

### ISSUE THREAD

**Issue by cnocula-i** [redhat-developer/gitops-operator#106]
Since ArgoCD finally released their 2.0.0 version (https://github.com/argoproj/argo-cd/releases/tag/v2.0.0), is there any roadmap or a rough timeline to incorporate it into the GitOps Operator? An info about a target month or quarter would be sufficient for me.

**Comment by iam-veeramalla** [comment]
Hi @cnocula-i , Gitop-Operator GA will is planned for next week will incorporate this.

**Comment by csantanapr** [comment]
I'm also looking to get an early drive with ArgoCD 2.0

**Comment by wtam2018** [comment]
v1.1 has been released.

**Comment by csantanapr** [comment]
@wtam2018 where can I get it?

It doesn't show up for me in operator hub openshift console 4.6
And I don't see an image catalog in quay https://quay.io/repository/redhat-developer/gitops-backend-operator-index?tag=latest&tab=tags
Or a release branch or tag on this repo.

**Comment by sbose78** [comment]
It would be visible in 4.7.

**Comment by csantanapr** [comment]
Hi @sbose78 

Could the operator be supported on OCP 4.6? IBM Cloud Managed OCP ROKS only supports 4.6 now, adding 4.7 in the future.

Also, a lot of openshift customers are expecting to stay on version 4.6 for a while because 4.6 is the [Red Hat OpenShift Extended Update Support (EUS)](https://access.redhat.com/support/policy/updates/openshift-eus)

**Comment by wtam2018** [comment]
It looks like we need to back port/release it to 4.6.   The same operator can work in 4.6 but we need a bundle for 4.6 as 4.6 uses an older version of Pipelines.

**Comment by csantanapr** [comment]
Thank you @wtam2018 this will mar possible for a ton of customers to give feedback and try openshift-gitops and kam

We are working on integrating the workflow in the Toolkit including RHACM 
https://cloudnativetoolkit.dev

**Comment by wtam2018** [comment]
@catrobson   My apology.  We haven't decided to backport to 4.6 as it was a Tech Preview release on 4.6.   However, the operator allows users to use an upstream argo cd image.   So, it is possible to use an argocd v2.0 image if you can't move to 4.7.

**Comment by wtam2018** [comment]
If you create a new Argo CD instance, you can specific the argocd image in the operator UI.
![create-argocd](https://user-images.githubusercontent.com/44041377/115437119-caf59780-a1d9-11eb-82b6-e8e987c9df62.png)

**Comment by iam-veeramalla** [comment]
@cnocula-i @csantanapr Is this issue good to be closed ?

**Comment by cnocula-i** [comment]
From my perspective yes.

**Comment by iam-veeramalla** [comment]
> From my perspective yes.

Thanks @cnocula-i
