### ISSUE TITLE
Upgrade operator-sdk to v1.6.2

### ISSUE THREAD

**Issue by wtam2018** [redhat-developer/gitops-operator#112]
### Is your task related to a problem? Please describe.

The version of operator-sdk currently used v0.19 is outdated without a question.   We should refresh with the new operator-sdk to 
Checkout what is new:
https://sdk.operatorframework.io/docs/building-operators/golang/migration/#what-is-new
and what has changed.
https://sdk.operatorframework.io/docs/building-operators/golang/migration/#what-was-changed

### Describe the solution you'd like

To migrate, we can follow these steps.
https://sdk.operatorframework.io/docs/building-operators/golang/migration/

### Describe alternatives you've considered

N/A.  It is about time to upgrade.  :-)

**Comment by iam-veeramalla** [comment]
we have upgrade to operator-sdk v1.11.0. This issue can be closed.
