### ISSUE TITLE
resource.customizations is deleted from argocd-cm configmap

### ISSUE THREAD

**Issue by nastacio** [redhat-developer/gitops-operator#117]
**Describe the bug**

Applying resource.customizations via argocd-cm configmap only works for a minute or two before being removed from the configmap and returning to having no health check customisations. The resource.customizations key is left in the configmap with an empty value.

I see an earlier description of the same symptom in [this issue](https://github.com/argoproj/argo-cd/issues/5056), though I am seeing the problem with recent versions of OpenShift:
- OpenShift 4.6 + GitOps operator 1.0.0 (Argo CD 1.8.4)
- OpenShift 4.7 + GitOps operator 1.1.0 (ArgoCD 2.0.0)

**To Reproduce**

(assuming OpenShift 4.7, but exact same behavior in 4.6)

- Deploy the OpenShift GitOps operator (1.1.0 currently) and wait for all pods to be up and running (less than a minute)
- Patch the `configmap/argocd-cm` object with the sample from https://argo-cd.readthedocs.io/en/stable/operator-manual/health/ 

```
health_file=/tmp/argo-health.yaml
cat<<EOF > ${health_file}
data:
  resource.customizations: |
    cert-manager.io/Certificate:
      health.lua: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.conditions ~= nil then
            for i, condition in ipairs(obj.status.conditions) do
              if condition.type == "Ready" and condition.status == "False" then
                hs.status = "Degraded"
                hs.message = condition.message
                return hs
              end
              if condition.type == "Ready" and condition.status == "True" then
                hs.status = "Healthy"
                hs.message = condition.message
                return hs
              end
            end
          end
        end

        hs.status = "Progressing"
        hs.message = "Waiting for certificate"
        return hs
EOF

kubectl patch configmap/argocd-cm \
            --namespace openshift-gitops \
            --type merge \
            --patch-file "${health_file}"

sleep 10

kubectl get configmap/argocd-cm --namespace openshift-gitops -ojsonpath='{.data.resource\.customizations}'
<empty line>
```

**Expected behavior**

```kubectl get configmap/argocd-cm --namespace openshift-gitops -ojsonpath='{.data.resource\.customizations}'```

should return the resource customization applied as a patch.

**Screenshots**

**Version**

```shell
argocd: v2.0.0+unknown
  BuildDate: 2021-04-09T04:17:22Z
  GitCommit: 
  GitTreeState: clean
  GoVersion: go1.15.7
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.0.0+unknown
  BuildDate: 2021-04-09T04:17:22Z
  GitTreeState: clean
  GoVersion: go1.15.7
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: unable to determine ksonnet version: exec: "ks": executable file not found in $PATH
  Kustomize Version: unknown 1970-01-01T00:00:00Z
  Helm Version: v3.5.0+6.el8+g77fb4bd
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0
```

**Logs**

[logs.zip](https://github.com/redhat-developer/gitops-operator/files/6429962/logs.zip)

**Comment by iam-veeramalla** [comment]
Hi @nastacio , Thanks for raising issue with us.

Operator reconciles on changes made to the argo cd resources and sets them back to default. This is an expected behaviour. Any changes that you require should be rather made as part of Argo CR.

Please add your customizations to argocd CR
```
cr.Spec.ResourceCustomizations
```
https://github.com/redhat-developer/gitops-operator/blob/6583f71f6525c2c03e0b59ea4924b7ebb9486971/deploy/crds/argoproj.io_argocds_crd.yaml#L677

This is the piece of code which sets the argo cd config map back to default.
https://github.com/argoproj-labs/argocd-operator/blob/3aa839b023883b564ac5bfd6012f16f9ce19797b/pkg/controller/argocd/configmap.go#L437

**Comment by nastacio** [comment]
@iam-veeramalla your solution works, which is fantastic for our immediate needs.

There is an odd inconsistency with other patches to that same `argocd-cm`, since I could patch the `repositories` parameter without it being reset.

I can understand the need to restructure the way the configuration is managed (moving it up from the ConfigMap to the ArgoCD object), but it seems like letting some portions of `argocd-cm` behave like in ArgoCD (e.g. `repositories` can be patched and is not reset) , but not others, will confuse a lot of people familiar with ArgoCD.

**Comment by iam-veeramalla** [comment]
Thanks @nastacio .. I will take a look at why changes in repositories is not reset by the controller.

**Comment by lachm99** [comment]
Hi @iam-veeramalla,
I'm encountering the same issue as @nastacio was facing, but in the ArgoCD CR rather than the ConfigMap.
I am updating the CR, but it will occasionally reset and completely remove my resource customizations.
