### ISSUE TITLE
provide option to disable clusterrolebinding for multitenancy

### ISSUE THREAD

**Issue by andras-babos** [redhat-developer/gitops-operator#121]
**issue**

We would like to provide argocd multitenancy inside one cluster, provide multiple argocd server instances in different namespaces, hand the administrative responsibility to the respective teams. The upstream argocd implementation fully supports this: https://github.com/argoproj/argo-cd/tree/master/manifests and the operator also supports multiple instances of argocd but it creates a clusterrolebinding for the $argocdinstance-application-controller service account which gives global read rights.
This global read right is allowing the account to read into system or other tenant resources and based on the link and our testing it's not strictly necessary.

**request**
We would like to install argocd instances which have kubernetes rbac permissions only on their own namespaces and only the operations team can give rbac permissions to individual namespaces for the service account. It would be good if there will be a parameter for the argocd instance to enable/disable the clusterrolebinding of the service account.

**Comment by sbose78** [comment]
> but it creates a clusterrolebinding for the $argocdinstance-application-controller service account which gives global read rights.

We are aware of this and we are classifying this as a bug which we are working on a fix on priority.


After the fix:
* the cluster config argocd in Openshift config namespace will have cluster-scoped read.
* Any other argocd will not have the cluster scoped read.


Would this help?

**Comment by andras-babos** [comment]
Thank you for the quick reply!
I don't see this "cluster config argocd in Openshift config namespace" in our system with `oc get argocd -A`, I suppose this will be a new feature? But as far as I understand this will be an internal, system component which isn't exposed to the end users, this way it will be good for us.

**Comment by andras-babos** [comment]
Upgraded and tested the 1.1.1 version today and it's working as expected, I will close this ticket.

**Comment by sbose78** [comment]
Thank you!
