### ISSUE TITLE
GitOps GA version could/should support OCP 4.6

### ISSUE THREAD

**Issue by nastacio** [redhat-developer/gitops-operator#128]
**Is your feature request related to a problem? Please describe.**
I see that the support statement for the operator (https://access.redhat.com/support/policy/updates/openshift#gitops) only mentions OCP 4.7.

That is somewhat limiting given that OCP 4.6 is a EUS release that will be in many enterprise data-centers [for at least another year or so](https://access.redhat.com/support/policy/updates/openshift).

**Describe the solution you'd like**
Assuming there are no technical hurdles (e.g. Argo versions incompatible with OCP 4.6 libraries, etc) , have the GA version of the GitOps operator supported on OCP 4.6.

**Describe alternatives you've considered**
The alternative is to convince customers in OCP 4.6 to run the GitOps operator in its preview format or wait to adopt the GitOps operator until they migrate to OCP 4.7.

**Additional context**

**Comment by iam-veeramalla** [comment]
GitOps v1.3.z supports OCP 4.6.
