### ISSUE TITLE
e2e tests fails running locally

### ISSUE THREAD

**Issue by iam-veeramalla** [redhat-developer/gitops-operator#143]
**Describe the bug**
e2e tests fails locally. Operator when run locally is not able to create workloads for ArgoCD instances created to manage Cluster Configuration.

Reported and fixed in upstream:
https://github.com/argoproj-labs/argocd-operator/pull/340

**To Reproduce**
Run operator locally
1. make test-e2e
2. log the operator -> `oc logs deploy/gitops-operator -n openshift-operators`

You will find the below error in logs

```
:"failed to initialise kube client","ArgoCD Namespace":"openshift-gitops","ArgoCD Name":"openshift-gitops","error":"unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined",
```

**Expected behavior**
e2e tests should pass

**Additional context**
NA

**Comment by amitkrout** [comment]
@iam-veeramalla Tested it locally on master branch. Still i can see the same error message in the log
```
{"level":"error","ts":1624620241.38273,"logger":"openshift_controller_argocd","msg":"failed to initialise kube client","ArgoCD Namespace":"openshift-gitops","ArgoCD Name":"openshift-gitops","error":"unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined",[...]}
```
And 

```
=== RUN   TestGitOpsService/Validate_Redhat_Single_sign-on_Configuration
[...]
    rhsso_test.go:110: configmaps "argocd-cm" not found
```
