### ISSUE TITLE
Do not install RHSSO OOTB for the default Argo CD instance in openshift-gitops namespace

### ISSUE THREAD

**Issue by iam-veeramalla** [redhat-developer/gitops-operator#159]
**Describe the bug**
The current behavior installs and configures OpenShift Login OOTB using RHSSO for default Argo CD instance. However the team has agreed to revoke this decision as OpenShift Login OOTB does not work on Vanilla OpenShift clusters or clusters without User Management.

Acceptance Criteria:
1. RHSSO should be only Installed and Configured when user explicitly modifies the Argo CD Custom Resource to add `.sso.provider: keycloak` in the Spec.
2. This is valid for both "default Argo CD instance(openshift-gitops ns)" and "Argo CD Instance in any other namespaces" 

**To Reproduce**
1. Run operator locally `operator-sdk run local`
2. Run `oc get pods -n openshift-gitops` to see that keycloak pods are running.
3. Go to Argo CD Console -> Login with Keycloak -> Login with OpenShift 
4. If you dont have any User Management configured on you OpenShift Cluster you will realise this option is useless or you will end up with an unsuccessful attempt to login using `kubeadmin` user.

**Expected behavior**
Do not install RHSSO OOTB for the default Argo CD instance in openshift-gitops namespace

**Screenshots**
NA

**Additional context**
NA

**Comment by amitkrout** [comment]
fixed via - https://github.com/redhat-developer/gitops-operator/pull/160
/close
