### ISSUE TITLE
Default ClusterRole/Binding for argocd-application-controller does not include CRs

### ISSUE THREAD

**Issue by rgordill** [redhat-developer/gitops-operator#169]
**Describe the bug**
Default ClusterRole/Binding for argocd-application-controller does not include CRs

**To Reproduce**
1. Install openshift-gitops
2. Install an operator
3. Try to sync a repo with CRs

**Expected behavior**
The CRs should be included in the ClusterRole `openshift-gitops-openshift-gitops-argocd-application-controller` or at least some docs that clarifies how to add them to it so gitops can handle those resources.

**Screenshots**

![strimzi](https://user-images.githubusercontent.com/21176597/125408629-66eb0580-e3bb-11eb-83ad-017d585bba92.png)

**Additional context**
I have installed the strimzi operator with openshift-gitops, and the strimzi namespace is create automatically by the application that should install the CR.

**Comment by davidkarlsen** [comment]
+1 This one is really important to get in place, or else the applicable use of argo is really limited.
We use a lot of CRs and usually create a clusterrole for each such onboarding, labelling them with `bac.authorization.k8s.io/aggregate-to-admin: "true"` in order to hand them out by scale.

I wish the role which each argo binds to can either be influenced by the CR creating argo-instances (gives better control), or that the instances bind to a common cluster-role, which can be aggregated to as described above.

**Comment by davidkarlsen** [comment]
Hmm, this does no longer seem to be a problem as of v1.2.1 of the operator? The role `argocd-argocd-application-controller` seems to include most/all CRs, but I cannot find anything in the changelog (or update of this issue), among them:
```
k get role argocd-argocd-application-controller  -o yaml|grep -i sealedse
  - sealedsecrets
```

**Comment by iam-veeramalla** [comment]
Hi @rgordill @davidkarlsen , There are a couple of ways in which you can extend the permissions of Argo CD application controller. 

1. By creating a new cluster role/ cluster role binding.
https://github.com/redhat-developer/gitops-operator/blob/master/docs/OpenShift%20GitOps%20Usage%20Guide.md#additional-permissions

2. Using custom cluster roles(if are talking about managing other namespaces)
https://github.com/redhat-developer/gitops-operator/blob/master/docs/OpenShift%20GitOps%20Usage%20Guide.md#deploy-resources-to-a-different-namespace-with-custom-role

**Comment by iam-veeramalla** [comment]
Please let me know if this can be closed.

**Comment by rgordill** [comment]
Dunno. After almost a year, maybe the documents are updated and there is no need for anything else. Maybe it is better to give full access to the whole cluster to the service account. Yes, you can close this issue, as I cannot tell if it is relevant with latests releases.

**Comment by davidkarlsen** [comment]
@iam-veeramalla I think it can be closed
