### ISSUE TITLE
v1.2: OOMKilled of openshift-repo-server after upgrade from 1.1.2

### ISSUE THREAD

**Issue by EagleIJoe** [redhat-developer/gitops-operator#184]
After upgrading from gitops operator 1.1.2 to 1.2.0, the repo-server crashloops with OOM ...

Removing the namespace resourcequota did not help.

**Comment by amitkrout** [comment]
@EagleIJoe On which cluster it is reported ? Screenshot and failure log would be helpful.

**Comment by jannfis** [comment]
Hey, we do apply some resource limits by default now which might be too low for some larger installations or when using custom plugins.

You can manually alter the limits in the ArgoCD CR. An example to increase memory limit for the repo-server:

```yaml
spec:
  repo:
    resources:
       limits:
         memory: <some value>
```

The default limit is 512Mi which _should_ be sufficient for most installations. You can also try and scale out the repo server workload by increasing its numbers of replicas to distribute workload across more pods.

**Comment by EagleIJoe** [comment]
Increasing the limit to 1Gi was sufficient for my setup.

**Comment by jannfis** [comment]
@EagleIJoe Thanks for confirmation. May I ask for details about your setup? I.e. do you use a mono repo? How many apps? What kind of toolings? This information could help us in fine-tuning resource requests in future releases, or at least provide some more guidance to users.

**Comment by EagleIJoe** [comment]
@jannfis @iam-veeramalla i have the following setup:
* OpenShift 4.7
* 100 Apps deployed via appsets
* 1 argocd repo server instance, 1 argocd server instance

So nothing major. What I am seeing now is the infamous "all SubConns are in TransientFailure" errors happening...

This was working fine in GitOps 1.1.2.
