### ISSUE TITLE
update the deprecated APIs

### ISSUE THREAD

**Issue by iam-veeramalla** [redhat-developer/gitops-operator#186]
Describe the bug
kubernetes 1.22 is End of life for deprecated APIs. 

The apiextensions.k8s.io/v1beta1 API version of CustomResourceDefinition will no longer be served in v1.22.

More information here:
https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes

To Reproduce
I was trying to install the GitOps 1.2 operator on a 4.9 cluster, but it failed to find one or more requirements:
api-server resource not found installing CustomResourceDefinition gitopsservices.pipelines.openshift.io: GroupVersionKind apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition not found on the cluster. This API may have been deprecated and removed, see https://kubernetes.io/docs/reference/using-api/deprecation-guide/ for more information.

Expected behavior
update the deprecated APIs

Additional context
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22

**Comment by wtam2018** [comment]
I believe this will be fixed by https://github.com/redhat-developer/gitops-operator/pull/136 operator-sdk upgrade.
