### ISSUE TITLE
Upgrade to argocd v2.1

### ISSUE THREAD

**Issue by davidkarlsen** [redhat-developer/gitops-operator#224]
**Is your feature request related to a problem? Please describe.**
https://github.com/argoproj/argo-cd/issues/5505 has some memory problems, these are fixed in 2.1.x

**Describe the solution you'd like**
Upgrade argocd to 2.1 by default in the operator.

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/argoproj/argo-cd/issues/5505

**Comment by jannfis** [comment]
GitOps Operator v1.3 will ship with Argo CD v2.1.x

**Comment by jannfis** [comment]
Reference issue: https://issues.redhat.com/browse/GITOPS-1298

**Comment by davidkarlsen** [comment]
Great - what's the GA date for that (ca)?

**Comment by jannfis** [comment]
We plan to release v1.3 just in time for OCP 4.9. Currently planned ETA is Oct. 14th. Disclaimer: This date may change.

Meanwhile, we released v1.2.1 which has a workaround for excessive memory consumption of the application controller, by introducing the new `.spec.controller.parallelismLimit` setting with a default value of `10`

**Comment by davidkarlsen** [comment]
> Meanwhile, we released v1.2.1 which has a workaround for excessive memory consumption of the application controller, by introducing the new `.spec.controller.parallelismLimit` setting with a default value of `10`

We're already on the operator version v1.2.1 with the parameter in place, but it still failed, which is why I'm looking for argo v2.1.x.

Bumping memory helped though, but from the graphs I see it's very spiky, so basically a lot of memory is burned just for the spikes.

**Comment by EagleIJoe** [comment]
This can be closed since the release 1.3.0 of the operator.

**Comment by iam-veeramalla** [comment]
upgraded to v2.1. Please feel free to re-open incase you notice any issues.
