### ISSUE TITLE
Dex Server doesn't return system:cluster-admins when integrated with OpenShift OAuth

### ISSUE THREAD

**Issue by sumantripuraneni** [redhat-developer/gitops-operator#246]
**Describe the bug**

OpenShift GitOps Operator v1.3 and integrated with Openshift OAuth using the Dex server.  Dex integration with OpenShift OAuth is working fine, however I find an issue with the Dex Server response where it responds with corresponding user groups back to ArgoCD after authentication. 

Dex is not providing a "system:cluster-admins" group in its response to ArgoCD along with other groups. 

For example: I am a cluster-admin on a cluster and part of other groups as well, however, in Dex response, I don't find "system:cluster-admins"

Example response from Dex to Gitops Server,
time="2021-11-03T15:30:14Z" level=info message="received unary call ............ groups: ["system:authenticated", system:authenticated:oauth", "container_users", "container_prod_users"] 

**To Reproduce**
1.  Add user to cluster admin 
oc adm policy add-cluster-role-to-user cluster-admin <<user name>>

2. Go to OpenShift Cluster (4.7.18) GUI console, Open the Administrator perspective of the web console and navigate to Operators → OperatorHub in the menu on the left.
Search for OpenShift GitOps, click the Red Hat OpenShift GitOps tile, and then click the Install button.

3. After the operator is installed, using the dropdown Actions on top right of the page, choose Edit Subscription
On the YAML code, under the spec level, enable the DEX feature to enable external authentication and click Save
spec:
  config:
    env:
      - name: DISABLE_DEX
        value: 'false'

4. Change the project to openshift-gitops, Go to the menu Operators>Installed Operators and click on Red Hat OpenShift GitOps, select tab Argo CD, On the ArgoCD instance list, click on the three dots at the very left of the openshift-gitops and select Edit ArgoCD,
On the YAML code, under the spec level, update the DEX and RBAC section to match the following.
...
spec:
  dex:
    openShiftOAuth: true
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, system:cluster-admins, role:admin
    scopes: '[groups]'
...

5. Login to ArgoCD UI (user with "cluster-admin" ), and in Open Shift GUI, Go to openshift-gitops project --> pods --> argocd-server-XXXX --> logs
6. See error
time="2021-11-03T15:30:14Z" level=info message="received unary call ............ groups: ["system:authenticated", system:authenticated:oauth", "container_users", "container_prod_users"] 

***system:cluster-admins is not part of Dex response

**Expected behavior**

Dex Server response should include "system:cluster-admins" as well along with other groups (such as "system:authenticated", "system:authenticated:oauth") when user part of "system:cluster-admins"

**Screenshots**

**Additional context**

**Comment by iam-veeramalla** [comment]
Hi @sumantripuraneni , Sorry for responding late on this. It somehow got missed. Do you still see this issue ? Can you share the oc command output to confirm that your user is part of `system:cluster-admin` group ?

If this really turns out to be true, we should work with `github.com/dex-idp/dex` to get this fixed.

**Comment by iam-veeramalla** [comment]
Any update on this @sumantripuraneni

**Comment by xukawalke** [comment]
@sumantripuraneni I can speak to this as we ran into this ourselves (not with this Operator, but Argo in general). The group you need is actually `cluster-admin` not `system:cluster-admin` if memory serves.

**Comment by RafalSkolasinski** [comment]
Fresh openshift install here using ROSA. The `argocd-rbac-cm` reads 
![image](https://user-images.githubusercontent.com/10928117/154754658-68ea88c9-1d7d-4c6b-bf11-e896f117cae8.png)
but Argo receives 

![image](https://user-images.githubusercontent.com/10928117/154754701-eedd402e-ec46-4986-b626-95c0a2a2ec13.png)

Specifying just `cluster-admins` instead of `system:cluster-admins` seems to solve the issue for me:
```
  rbac:
    policy: g, cluster-admins, role:admin
    scopes: '[groups]'
```

**Comment by iam-veeramalla** [comment]
This issue is fixed in the latest version of the Operator. 

Both `system:ckuster-admins` and `cluster-admins` is part of the default RBAC now.
