### ISSUE TITLE
argocd-tls-certs-cm is overwritten by the operator (v1.4.0)

### ISSUE THREAD

**Issue by iam-veeramalla** [redhat-developer/gitops-operator#271]
**Describe the bug**
Prior to v1.4.0 of OpenShift GitOps, certificates for TLS validation could be managed via the ArgoCD GUI or by controlling the argocd-tls-certs-cm ConfigMap directly. The value of argocd-tls-certs-cm was set initially when ArgoCD was deployed but not altered thereafter.

After upgrading to v1.4.0, this ConfigMap is reset to the value of tls.intitialCerts in the ArgoCD CR after any change. This renders the certificate management via the GUI or previous direct ConfigMap control useless and deletes any certificates that were added to the ConfigMap prior to the upgrade.

Workaround:  Add the needed cert to ArgoCD CR spec  tls.initialCerts.  See https://argocd-operator.readthedocs.io/en/latest/reference/argocd/#tls-options

**Additional context**

**Comment by iam-veeramalla** [comment]
The change in the behavior is due to the result of `controller-runtime` update to v0.11.0. This upgrade was required to update Argo CD to v2.2.2.

### Background:
Argo CD allows users to provide Initial set of certificates in the argocd-tls-certs-cm ConfigMap for connecting to Git repositories via HTTPS. Any user with the permissions to access configmap can manage the certificates.

### Issue:
Any certificates added directly to the argocd-tls-certs-cm ConfigMap are overridden by the operator to the defaults provided in .spec.tls.initialCerts of Argo CD CR.

### Reason:
Argo CD Operator manages the contents(certificates) of argocd-tls-certs-cm ConfigMap using .spec.tls.initialCerts property in the Argo CD CR as shown here

### Workaround or Solution:
Instead of updating the argocd-tls-certs-cm ConfigMap with the certificates, Please use .spec.tls.initialCerts property in the Argo CD CR. An example for the same is provided below.
https://github.com/iam-veeramalla/openshift-gitops-examples/blob/master/argocd/GITOPS-1725/argocd-initialTLScerts.yaml

### TBH, this does not sound to me like a bug. Argo CD operator reconciling on changes to the argocd-tls-certs-cm ConfigMap and setting it back to the defaults should be the expected behavior. When I tested the old versions of operator .spec.tls.initialCerts property in the Argo CD CR does not even seem to work. That might be the reason why users have adopted to update argocd-tls-certs-cm ConfigMap directly.

**Comment by jannfis** [comment]
Has this been fixed with any of the recent 1.4.z releases, @iam-veeramalla ?

**Comment by iam-veeramalla** [comment]
Hi @jannfis yes.

**Comment by jannfis** [comment]
Thanks. Then we'll be closing this issue :)
