### ISSUE TITLE
Feature: add `s390x` support

### ISSUE THREAD

**Issue by skuethe** [redhat-developer/gitops-operator#278]
**Is your feature request related to a problem? Please describe.**
OpenShift GitOps Operator is currently not available on OpenShift running on `s390x`.

**Describe the solution you'd like**
Add `s390x` arch to the build automation, so that multi arch operator images can be made available and therefor be used on `s390x` environments.

**Additional context**
I know that argocd is currently not available as `s390x` image. And any changes to the operator should probably wait until that has changed.
There are currently two open PRs (I found) which look into adding multi arch support for ArgoCD (currently based on `ppc64le`):

- https://github.com/argoproj/argo-cd/pull/6441 (on hold because of `aws cli` dependencies)
- https://github.com/argoproj/argo-cd/pull/8155 (on hold in favor of 6441)

Still wanted to open this issue to keep track of it.

As a bonus:
Maybe somebody from Red Hat can look into this and add some priorities on these open PRs? :)

Thanks.

**Comment by levivic** [comment]
@skuethe the Red Hat and IBM partner program has just started the s390x support of RedHat gitops, the porting efforts will follow shortly. What's your context of this request? Do you have clients requesting it? If you want to know more details about the plan of the porting work and s390x release, feel free to contact me.

**Comment by skuethe** [comment]
> @skuethe the Red Hat and IBM partner program has just started the s390x support of RedHat gitops, the porting efforts will follow shortly. What's your context of this request? Do you have clients requesting it? If you want to know more details about the plan of the porting work and s390x release, feel free to contact me.

That is good to hear @levivic . Yes I have a client running OpenShift on s390x in production - or rather trying it, as unfortunately a lot of operators are still missing. So getting any feedback to the current state would be much appreciated!

**Comment by levivic** [comment]
@skuethe no problems. IBM and Red Hat partner/synergy program are working hard on bringing more and more RH products to OCP on z. And many have already been enabled like EAP, SSO, RHDG..... Do you want to share more details about your client? Urgency? With those info, the ibm team could also evaluate and prioritize this task accordingly.

**Comment by levivic** [comment]
hi @skuethe FYI, there is a PR created to support s390x, https://github.com/argoproj/argo-cd/pull/8890. however similar issue with missing dependency aws-cli.

**Comment by skuethe** [comment]
Thanks for keeping me in the loop - was already subscribed to that PR :)

**Comment by skuethe** [comment]
So, https://github.com/argoproj/argo-cd/pull/8890 got merged - 🥳
Looking forward for the next release of argocd and the next steps in getting this operator supported on these other archs :)

**Comment by iam-veeramalla** [comment]
[GITOPS-2014](https://issues.redhat.com/browse/GITOPS-2014)  is the JIRA for internal tracking.

**Comment by skuethe** [comment]
Some updates to the progress: `argo-cd v2.4.0` released three days ago:
https://github.com/argoproj/argo-cd/releases/tag/v2.4.0

> Power PC and IBM Z Support
>
> The list of supported architectures has been expanded, and now includes IBM Z (s390x) and PowerPC (ppc64le). Starting with the v2.4 release the official quay.io
repository is going to have images for amd64, arm64, ppc64le, and s390x architectures.

And the official tracking ticket now seems to be this one:
https://issues.redhat.com/browse/GITOPS-1836

**Comment by Joshua-Beha** [comment]
It looks like the official tracking ticket mentioned by @skuethe  has since been closed, does this mean s390x is now supported?

**Comment by wtam2018** [comment]
Yes, s390x is supported since OpenShift GitOps v1.6.0.  We can close this ticket.

**Comment by Joshua-Beha** [comment]
@wtam2018 Where is the s390x operator available? I am unable to find an s390x image either on quay.io (if it is on quay.io it may be worth clarifying where in the README) or on registry.redhat.io. The x86 operator is available from registry.redhat.io [here](https://catalog.redhat.com/software/containers/openshift-gitops-1/gitops-operator-bundle/6052132e31412999c804b506) so I think it would be best if the s390x operator was also available from the same location.

**Comment by levivic** [comment]
hi @Joshua-Beha the link you have in redhat is actually the operator bundle image, which is arch neutral. I found the operator link at https://catalog.redhat.com/software/containers/detail/604292365a00810ecaf7bcfe?tag=v1.8.2-5&push_date=1680795871000. @wtam2018 i do notice the operator link isn't properly included in the Component section in the Gitops product page https://catalog.redhat.com/software/container-stacks/detail/5fb288c70a12d20cbecc6056. And the existing `operator` link there actually points to the bundle image, which is confusing for customers.

**Comment by Joshua-Beha** [comment]
Gotcha, thanks for your help @levivic. I was definitely looking in the wrong place.
