### ISSUE TITLE
Make the operator manage argocd-tls-certs-cm again

### ISSUE THREAD

**Issue by GerbenWelter** [redhat-developer/gitops-operator#284]
When 1.4.0 came out I was caught off guard by the operator managing the argocd-tls-certs-cm. But once I found that this ConfigMap was managed by the operator like all other ConfigMaps I agreed this was the better solution.

Yesterday I was testing some unrelated changes to our Ansible playbooks for deploying and configuring new OpenShift clusters. I couldn't understand why ArgoCD wouldn't trust our internal repository anymore. It literally took me hours to find out that the **empty** argocd-tls-certs-cm ConfigMap on the newly installed cluster wasn't replaced by the operator anymore. Just by chance I noticed on another cluster that the operator had been updated to 1.4.3 which led me here.

I understand that the behavior introduced in 1.4.0 may have affected lots of people including me but I understood the change. It brought more consistency to the way the operator worked. I adjusted the provisioning and moved on. Now with 1.4.3 the behavior is changed again in a less intuitive way. Now you either need to decide to just use the ConfigMap or use the ArgoCD object but you need to delete the ConfigMap so the operator can create it again. The first way is inconsistent with other ConfigMaps and the latter makes it more error prone.

My request is to revert the change introduced in #283 and give complete control back to the operator. It just makes more sense.

**Comment by jannfis** [comment]
TBH, I think we should not revert the change as a whole. I propose the following instead:

For people wanting to manage all of their repository certificates using the Operator, and have it overwrite any manual changes made via CLI/API or directly to the ConfigMap, we can introduce a new field `certs`, which doesn't consider the existence of the ConfigMap or its contents and will just reconcile upon changes to that field.

WDYT?

**Comment by iam-veeramalla** [comment]
Hi @GerbenWelter , I was in the same lines during release v1.4.0. 

A lot of users reported issue on v1.4.0 that they cannot add certs anymore to `argocd-tls-certs-cm`. We had many discussions within the team and with the users.

As per the outcome of the discussions, the `initialCerts` field in the operator is only designed to configure Argo CD with Initial set of certificates to use upon creation of the cluster. Updating this property after the cluster has been created has no affect and should be used only as a means to initialize the cluster with the value provided. New certificates should then be added directly to  the `argocd-tls-certs-cm` configmap.

**Comment by iam-veeramalla** [comment]
> TBH, I think we should not revert the change as a whole. I propose the following instead:
> 
> For people wanting to manage all of their repository certificates using the Operator, and have it overwrite any manual changes made via CLI/API or directly to the ConfigMap, we can introduce a new field `certs`, which doesn't consider the existence of the ConfigMap or its contents and will just reconcile upon changes to that field.
> 
> WDYT?

@jannfis thats a nice suggestion. We can consider this as a new feature request.

**Comment by GerbenWelter** [comment]
@iam-veeramalla I understand your reasoning but doing this with a patch level update was unexpected.

So, if I understand your suggesting correctly:

The current field `initialCerts` is used for bootstrapping ArgoCD and will keep working for trusting a bootstrap repository regardless of the state of `argocd-tls-certs-cm`?
A possibly new field `certs` will consolidate any of the certs it specifies with user created certs in `argocd-tls-certs-cm`?

If that's the case I think that's a fine solution.

**Comment by jannfis** [comment]
> doing this with a patch level update was unexpected

I think it was the right thing to do. There was a bug introduced with v1.4.0 (which led the Operator to overwrite changes made by the user, which it has previously not done), and which has been fixed in its z-stream. Or is the behavior now different from pre-v1.4.0?

> The current field initialCerts is used for bootstrapping ArgoCD and will keep working for trusting a bootstrap repository regardless of the state of argocd-tls-certs-cm

The behavior for initialCerts would not change. If the `argocd-tls-certs-cm` exists, the reconciliation process for `initialCerts` would be a no-op, leaving the ConfigMap alone.

> A possibly new field certs will consolidate any of the certs it specifies with user created certs in argocd-tls-certs-cm

It will not consolidate. It will overwrite. There is no way to know for the Operator if a cert in `argocd-tls-certs-cm` was created by the user, or by the Operator. So with `certs` being specified, the control over `argocd-tls-certs-cm` will be solely in the hands of the Operator, not allowing any changes made by Argo CD through UI, CLI or declarative changes to `argocd-tls-certs-cm`.

**Comment by GerbenWelter** [comment]
OK, thanks for the explanation. I have adapted my provisioning to manage `argocd-tls-certs-cm` directly again.
