### ISSUE TITLE
drp: drop use of redis

### ISSUE THREAD

**Issue by davidkarlsen** [redhat-developer/gitops-operator#305]
### Is your task related to a problem? Please describe.
https://blog.argoproj.io/argo-cd-v2-3-release-candidate-a5b8cf11b0d3 states "Redis is no longer used during SSO login ([#8241](https://github.com/argoproj/argo-cd/pull/8241))" but still a redis deployment seems to hang around and there is no way to disable it.

### Describe the solution you'd like
Drop the redis pod

### Describe alternatives you've considered
N/A

### Additional context
there is a redis section exposed in the CRD for argocd - is it only used for auth - or for other uses too?

**Comment by jannfis** [comment]
Redis is an integral part of Argo CD and used for a lot of things regarding caching. It can't be dropped.

**Comment by davidkarlsen** [comment]
Thanks for the info

**Comment by davidlanouette** [comment]
This appears to not be an open issue.  Can a maintainer close it?
