### ISSUE TITLE
GitOps operator 1.6 doesn't support "Create local accounts"

### ISSUE THREAD

**Issue by louise-zhang** [redhat-developer/gitops-operator#363]
**Describe the bug**
GitOps operator 1.6 doesn't support "Create local accounts"

**To Reproduce**

Edit argocd-cm ConfigMap
```
oc edit cm argocd-cm

data:
  accounts.local-user: 'apiKey,login'
```

**Expected behavior**
New users should be created and can be used to login to ArgoCD server with token, this is working in GitOps operator 1.5.5. But the change doesn't apply to configmap for GitOps operator 1.6.0

**Comment by jannfis** [comment]
Hi @louise-zhang,

please use the `extraConfig` in the Operand from 1.6.0 onwards, e.g.

```
spec:
  extraConfig:
    accounts.local-user: 'apiKey,login'
```

**Comment by louise-zhang** [comment]
Thanks @jannfis, that works

**Comment by louise-zhang** [comment]
Adding `extraConfig` to ArgoCD instance works
