### ISSUE TITLE
Resource Customizations in ArgoCD CR are removed

### ISSUE THREAD

**Issue by lachm99** [redhat-developer/gitops-operator#374]
**Describe the bug**
Resource customizations applied to the ArgoCD CR `openshift-gitops` are completely removed and overwritten periodically.

**To Reproduce**

1. Install the OpenShift Gitops operator (version 1.5.6)
2. Inspect the `ArgoCD/openshift-gitops` resource.
3. Add the following to the `spec` section:
    ```
        resourceCustomizations: |
          operators.coreos.com/Subscription:
            health.lua: |
              health_status = {}
              if obj.status ~= nil then
                if obj.status.conditions ~= nil then
                  numDegraded = 0
                  numPending = 0
                  msg = ""
                  for i, condition in pairs(obj.status.conditions) do
                    msg = msg .. i .. ": " .. condition.type .. " | " .. condition.status .. "\n"
                    if condition.type == "InstallPlanPending" and condition.status == "True" then
                      numPending = numPending + 1
                    elseif (condition.type == "InstallPlanMissing" and condition.reason ~= "ReferencedInstallPlanNotFound") then
                      numDegraded = numDegraded + 1
                    elseif (condition.type == "CatalogSourcesUnhealthy" or condition.type == "InstallPlanFailed" or condition.type == "ResolutionFailed") and condition.status == "True" then
                      numDegraded = numDegraded + 1
                    end
                  end
                  if numDegraded == 0 and numPending == 0 then
                    health_status.status = "Healthy"
                    health_status.message = msg
                    return health_status
                  elseif numPending > 0 and numDegraded == 0 then
                    health_status.status = "Progressing"
                    health_status.message = "An install plan for a subscription is pending installation"
                    return health_status
                  else
                    health_status.status = "Degraded"
                    health_status.message = msg
                    return health_status
                  end
                end
              end
              health_status.status = "Progressing"
              health_status.message = "An install plan for a subscription is pending installation"
              return health_status
    ```
5. Monitor. Sometimes reversion is immediate, sometimes it takes an extended period. (Several hours, days even?)

**Expected behavior**
I expected my resource customization to apply and remain, however, it applies and works as expected, but for an indeterminate amount of time before being overwritten and reset.

**Additional context**
Note Issue #117, with a similar problem. However, the solution there is to make the edits to this resource rather than the CM.

**Comment by jannfis** [comment]
Hm, that's weird. The Operator shouldn't touch that part of the CR for the default instance. It should only touch resource assignments:

https://github.com/redhat-developer/gitops-operator/blob/4b751128a52076d92c59e061de423c77bfa54c72/controllers/gitopsservice_controller.go#L356

We'll look into that.

**Comment by lachm99** [comment]
Hi @jannfis , 
We've identified a piece of our automation that was applying patches to the resource - and we suspect that those patches were responsible for resetting our resourcecustomizations.

Apologies for any inconvenience caused!
Thanks
