### ISSUE TITLE
Unable to install the ArgoCD operator after installing gitops operator

### ISSUE THREAD

**Issue by makambalaji** [redhat-developer/gitops-operator#56]
**Description**:
 Unable to install the ArgoCD operator after installing gitops operator

**Prerequisite**:
Install the GitOps operator

**Steps to Reproduce**:
1. Select the ArgoCD namespace
2. Navigate to Operator Hub
3. Search and select the "ArgoCD" operator
4. click Install on side pane

**Expected**:
Install operator page should be displayed with create button enabled

**Actual**:
`Operator Conflicts exists` error displays
![image](https://user-images.githubusercontent.com/61005404/108212355-c702b600-7153-11eb-94d5-af842c6fdb45.png)

**Comment by wtam2018** [comment]
Argo CD Operator and GitOps Operator register same set of CRDs.   They are designed to co-exist.

**Comment by iam-veeramalla** [comment]
This issue can be closed.
> Argo CD Operator and GitOps Operator register same set of CRDs. They are designed to co-exist.
