### ISSUE TITLE
Fix Kam Image reconcliation during upgrades

### ISSUE THREAD

**Issue by iam-veeramalla** [redhat-developer/gitops-operator#563]
**Describe the bug**
GitOps operator does not handle the KAM image upgrades during the GitOps operator upgrades. For example, when a user upgrades from GitOps operator v1.8.0 to v1.9.0, KAM image is not upgraded to the v1.9.0 supported version. 

However, someone who installs GitOps operator v1.9.0 can use the KAM v1.9.0 supported version.

**To Reproduce**
1. Install GitOps Operator v1.8.0
2. Verify KAM version
3. Upgrade GitOps Operator to v1.9.0
4. Verify KAM version

**Expected behavior**
GitOps operator handles the KAM Image version upgrade during the reconciliation.

**Screenshots**

**Additional context**

**Comment by svghadi** [comment]
fixed with
- https://github.com/redhat-developer/gitops-operator/pull/625 in master
- https://github.com/redhat-developer/gitops-operator/pull/605 in v1.10
- https://github.com/redhat-developer/gitops-operator/pull/565 in v1.9
