### ISSUE TITLE
Operator stuck on 1.7.2 and can't upgrade it

### ISSUE THREAD

**Issue by garyd2** [redhat-developer/gitops-operator#598]
**Describe the bug**
Automatic updates are not working on the operator in 1 of my 3 clusters

**To Reproduce**
![Screenshot 2023-09-08 at 17 33 20](https://github.com/redhat-developer/gitops-operator/assets/114586171/00a4e861-acb6-4345-abaa-a8f04221682a)

**Expected behavior**
If I click on Update channel and change it to gitops-1.9 or gitops-1.0 I get an error
![Screenshot 2023-09-08 at 15 29 27](https://github.com/redhat-developer/gitops-operator/assets/114586171/1920f226-7a9a-4b70-8b9f-91fb79a028e9)

**Screenshots**

**Additional context**

**Comment by garyd2** [comment]
I got an email about CVEs in 1.8 so I really need to update. Any advise, this is production environment so I cant really delete it and start again.

**Comment by garyd2** [comment]
Also `team-gitops@redhat.com <team-gitops@redhat.com>` doesn't exist it seems, It bounced back.

**Comment by garyd2** [comment]
@chetan-rns would you have any ideas on this issue, thanks a lot.

**Comment by garyd2** [comment]
Thanks @chetan-rns yes the UI shows the same error everytime, I have 3 Openshift clusters all with the GitOps operator and only 1 of them won't update.  
Is the operator watching for changes and that won't let me update it in the UI, is there a command I can run to update it via the cli?  Thanks so much for responding to me, sorry to have to @ mention you but I was desperate to get this fixed.

**Comment by garyd2** [comment]
![Screenshot 2023-09-21 at 17 07 39](https://github.com/redhat-developer/gitops-operator/assets/114586171/162ace80-935a-4e30-826e-98aa66c5aadc)
As you can see, update channel is set to latest which is `V1.9.2` at the min yet the installed version is `1.72` and I need to get to at least `1.8` for CVE fixes.  Any tips at all to get there is much appreciated as the subscription is not working as it should here.

**Comment by arjunprasad2143** [comment]
@garyd2 Just restart the olm pods to get the new new install plans. We had the same issues after changing the channel the new IPs were not coming automatically.

**Comment by garyd2** [comment]
The only olm pod I could find was the `olm-operator` pod in `openshift-operator-lifecycle-manager` NS. I restarted that and I was able to select the update channel now without error, Thanks @arjunprasad2143

**Comment by garyd2** [comment]
The operator updates  just don't seem to work.
i have 3 Openshift Clusters running  `4.13.11_1540` and 3 GitOps Operators
One is at ArgoCD `2.5.11`
One is at ArgoCD `2.8.3`
One is at ArgoCD `2.6.7`

Can anyone help with this, there is no consistency between the versions and 3 identical environments

**Comment by chetan-rns** [comment]
Hi @iam-veeramalla @jaideepr97, is this a known known issue? @garyd2 If possible, can you please provide the version of the GitOps operator in these clusters? Maybe different GitOps versions are running in these environments. 

https://docs.openshift.com/gitops/1.10/release_notes/gitops-release-notes.html

**Comment by garyd2** [comment]
One cluster is on 1.72 as per the title of the ticket and It won't upgrade
One cluster is on 1.10
One cluster is on 1.10

**Comment by garyd2** [comment]
![Screenshot 2023-10-16 at 14 09 10](https://github.com/redhat-developer/gitops-operator/assets/114586171/4c9ff463-f3bc-4444-a677-da5868d8f863)

**Comment by garyd2** [comment]
@chetan-rns @jaideepr97 anyone have any further insights on this? Thanks

**Comment by garyd2** [comment]
https://access.redhat.com/solutions/6603001 fixed it
