### ISSUE TITLE
(Extra)VolumeMount for appset controller

### ISSUE THREAD

**Issue by appiepollo14** [redhat-developer/gitops-operator#620]
**Describe the bug**
Adding an (extra)volume(mount) to the  appset controller via the ArgoCD spec is undone by the GitOps operator. Therefore the workaround proposed for this issue https://github.com/argoproj/argo-cd/issues/9607 cannot be implemented. 

**Expected behavior**
Allow (extra)volume(mounts) to be set on the applicationSet controller via the ArgoCD spec and not be removed by the GitOps operator.

**Comment by svghadi** [comment]
We recently added support for extra volumes for the `argocd-server` and `application-controller` components. I don't see any reason not to support it for the appset component as well.

**Comment by appiepollo14** [comment]
@svghadi Can you link me the pr containing the changes you mention. I would like to give it a try opening a pr for the appset controller

**Comment by svghadi** [comment]
That would be awesome. Below are 2 PRs for reference. The change will go into upstream project of gitops-operator, i.e [argocd-operator](https://github.com/argoproj-labs/argocd-operator). 

- https://github.com/argoproj-labs/argocd-operator/pull/455
- https://github.com/argoproj-labs/argocd-operator/pull/1477

**Comment by appiepollo14** [comment]
@svghadi linked PR ready for your review
