### ISSUE TITLE
Configure ArgoCD during deployment

### ISSUE THREAD

**Issue by pburgisser** [redhat-developer/gitops-operator#90]
Hello,

If I understand correctly the way the GitOps Operator works, the post-configuration of ArgoCD such as authentication with OIDC has to be done after the installation of the Operator itself through patching the ArgoCD onject. Is there a way to push the ArgoCD configuration while instancianting the GitOps Operator? I don't see much information in the GitOpsService CRDs.

The goal of this is to automate the installation of OCP + GitOps and avoid any post-install patching.

Thanks!

**Comment by wtam2018** [comment]
I don't know if there is a way currently other than there are some environment variables can be set in the subscription to affect the argocd instance.

**Comment by davidkarlsen** [comment]
@pburgisser also see https://github.com/redhat-developer/gitops-operator/issues/91

**Comment by iam-veeramalla** [comment]
@pburgisser we are working on automating the Auth Integration with Keycloak and Openshift IDP in 1.2. For now the process has to be manually done as Dex is disabled by default. 

Steps to Setup Dex are available here:
https://docs.google.com/document/d/1147S5yOdj5Golj3IrTBeeci2E1CjAkieGCcl0w90BS8/edit?ts=602bd66f#

**Comment by secustor** [comment]
@iam-veeramalla  The google drive link requires an authorization. Can you publish this somewhere, as a gist for example?

**Comment by iam-veeramalla** [comment]
> @iam-veeramalla  The google drive link requires an authorization. Can you publish this somewhere, as a gist for example?
 
@sabre1041 Do you have any documentation or gist for Dex ? Thanks in advance :)

**Comment by ThinkBriK** [comment]
In the same idea, it would be nice to be able to provide _applicationsSets_ on operator install to be able to configure a cluster automatically.

**Comment by iam-veeramalla** [comment]
Dex is installed and configured OOTB for OpenShift Login from 1.3.0.
