### ISSUE TITLE
admin pw is salted

### ISSUE THREAD

**Issue by davidkarlsen** [redhat-developer/gitops-operator#93]
**Describe the bug**

**To Reproduce**
1. install gitops operator and create an argo CR with default settings to create an instance
2. introspect secret for admin
3. see that it is salted (i.e starts with $"

**Expected behavior**
A cleartext pw which can be used to login as admin

**Screenshots**
N/A

**Additional context**
N/A

**Comment by iam-veeramalla** [comment]
Hi @davidkarlsen Why do you think admin password should be in plain text ? It is salted for security purpose.

**Comment by davidkarlsen** [comment]
> Hi @davidkarlsen Why do you think admin password should be in plain text ? It is salted for security purpose.

In the demo videos thats how they get in. With SSO default disabled and the admin pw unknown - one needs creds to get in.

**Comment by jannfis** [comment]
I think you might be looking at the wrong secret. The clear-text password is not stored in `argocd-secret` but in the secret named `<instance>-cluster`.

**Comment by davidkarlsen** [comment]
Thanks - that was it. So stored once secure, and once insecure then :-D
